In [11]:
import numpy as np
import pandas

In [2]:
def sigmoid(z):
    s = 1 / (1 + np.exp(-z))
    return s

In [3]:
def initialize_with_zeros(dim):
    w = np.zeros(shape=(dim, 1))
    b = 0
    return w, b

In [4]:
def propagate(w, b, X, Y):
    m = X.shape[1]
    
    # FORWARD PROPAGATION (FROM X TO COST)
    A = sigmoid(np.dot(w.T, X) + b)  # compute activation
    cost = (- 1 / m) * np.sum(Y * np.log(A) + (1 - Y) * (np.log(1 - A)))  # compute cost
    
    # BACKWARD PROPAGATION (TO FIND GRAD)
    dw = (1 / m) * np.dot(X, (A - Y).T)
    db = (1 / m) * np.sum(A - Y)
    
    grads = {"dw": dw,
             "db": db}
    
    return grads, cost

In [6]:
def optimize(w, b, X, Y, num_iterations, learning_rate, print_cost = False):    
    costs = []
    
    for i in range(num_iterations):       
        # Cost and gradient calculation 
        grads, cost = propagate(w, b, X, Y)
        
        # Retrieve derivatives from grads
        dw = grads["dw"]
        db = grads["db"]
        
        # update rule (≈ 2 lines of code)
        w = w - learning_rate * dw  # need to broadcast
        b = b - learning_rate * db
        
        # Record the costs
        if i % 100 == 0:
            costs.append(cost)
        
        # Print the cost every 100 training examples
        if print_cost and i % 100 == 0:
            print ("Cost after iteration %i: %f" % (i, cost))
    
    params = {"w": w,
              "b": b}
    
    grads = {"dw": dw,
             "db": db}
    
    return params, grads, costs

In [7]:
def predict(w, b, X):
    m = X.shape[1]
    Y_prediction = np.zeros((1, m))
    w = w.reshape(X.shape[0], 1)
    
    # Compute vector "A" predicting the probabilities of a cat being present in the picture
    A = sigmoid(np.dot(w.T, X) + b)
    
    for i in range(A.shape[1]):
        # Convert probabilities a[0,i] to actual predictions p[0,i]
        Y_prediction[0, i] = 1 if A[0, i] > 0.5 else 0
        
    return Y_prediction

In [8]:
def model(X_train, Y_train, X_test, Y_test, num_iterations=10, learning_rate=0.5, print_cost=False):
    # initialize parameters with zeros 
    w, b = initialize_with_zeros(X_train.shape[0])

    # Gradient descent 
    parameters, grads, costs = optimize(w, b, X_train, Y_train, num_iterations, learning_rate, print_cost)
    
    # Retrieve parameters w and b from dictionary "parameters"
    w = parameters["w"]
    b = parameters["b"]
    
    # Predict test/train set examples (≈ 2 lines of code)
    Y_prediction_test = predict(w, b, X_test)
    Y_prediction_train = predict(w, b, X_train)


    # Print train/test Errors
    print("train accuracy: {} %".format(100 - np.mean(np.abs(Y_prediction_train - Y_train)) * 100))
    print("test accuracy: {} %".format(100 - np.mean(np.abs(Y_prediction_test - Y_test)) * 100))

    
    d = {"costs": costs,
         "Y_prediction_test": Y_prediction_test, 
         "Y_prediction_train" : Y_prediction_train, 
         "w" : w, 
         "b" : b,
         "learning_rate" : learning_rate,
         "num_iterations": num_iterations}
    
    return d

In [12]:
import csv

In [34]:
def reader(name_file):
    results = []
    with open(name_file) as csvfile:
        reader = csv.reader(csvfile, quoting=csv.QUOTE_NONNUMERIC) # change contents to floats
        for row in reader: # each row is a list
            results.append(row)
        return results

In [35]:
results = reader("X_train.csv")
results = np.asarray(results)
results

array([[-1., -1., -1., -1.,  1.,  1., -1., -1., -1.,  1., -1.,  1.,  1.,
         1., -1., -1., -1.,  1., -1., -1., -1., -1.,  1., -1., -1.],
       [ 1., -1.,  1., -1., -1., -1., -1.,  1., -1., -1., -1.,  1.,  1.,
         1., -1.,  1., -1., -1., -1.,  1.,  1., -1., -1., -1.,  1.],
       [ 1., -1., -1., -1., -1.,  1., -1., -1., -1.,  1., -1.,  1.,  1.,
         1., -1., -1., -1.,  1., -1., -1., -1., -1.,  1., -1., -1.],
       [-1., -1.,  1., -1.,  1., -1., -1.,  1., -1., -1., -1.,  1.,  1.,
         1., -1.,  1., -1., -1., -1.,  1.,  1., -1., -1., -1.,  1.],
       [ 1., -1., -1., -1.,  1.,  1., -1., -1., -1.,  1., -1.,  1.,  1.,
         1., -1., -1., -1.,  1., -1., -1., -1., -1., -1., -1., -1.],
       [-1., -1.,  1., -1., -1., -1., -1.,  1., -1., -1., -1.,  1.,  1.,
         1., -1.,  1., -1., -1., -1.,  1.,  1., -1.,  1., -1.,  1.],
       [ 1., -1., -1., -1.,  1.,  1., -1., -1., -1.,  1., -1.,  1.,  1.,
         1., -1., -1., -1.,  1., -1., -1., -1.,  1.,  1.,  1., -1.],
      

In [36]:
results.shape

(12, 25)

In [37]:
a = results.T
a

array([[-1.,  1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.],
       [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.],
       [-1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1.],
       [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.],
       [ 1., -1., -1.,  1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.],
       [ 1., -1.,  1., -1.,  1., -1.,  1.,  1., -1.,  1.,  1., -1.],
       [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.],
       [-1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1.],
       [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.],
       [ 1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1., -1.,  1.],
       [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [-1., -1., -1., -1., -1., -

In [33]:
a.shape

(25, 12)

In [38]:
y = reader("Y_train.csv")
y = np.asarray(y)
y

array([[ 1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.]])

In [39]:
y.shape

(1, 12)