In [1]:
import numpy as np
import csv

In [2]:
def sigmoid(z):
    s = 1 / (1 + np.exp(-z))
    return s

In [293]:
def initialize_parameters(n_x, n_h, n_y):
    np.random.seed(1)
    
    W1 = np.random.randn(n_h, n_x) * 0.01 #W1 -- weight matrix of shape (n_h, n_x)
    b1 = np.zeros(shape=(n_h, 1))         #b1 -- bias vector of shape (n_h, 1)
    W2 = np.random.randn(n_y, n_h) * 0.01 #W2 -- weight matrix of shape (n_y, n_h)
    b2 = np.zeros(shape=(n_y, 1))         #b2 -- bias vector of shape (n_y, 1)

    parameters = {"W1": W1,
                  "b1": b1,
                  "W2": W2,
                  "b2": b2}
    
    return parameters

In [294]:
def forward(X,parameters):
    
    W1 = parameters["W1"]
    W2 = parameters["W2"]
    b1 = parameters["b1"]
    b2 = parameters["b2"]
    
    Z1 = np.dot(W1, X) + b1
    A1 = sigmoid(Z1)
    Z2 = np.dot(W2, A1) + b2
    A2 = sigmoid(Z2)
    
    
    cache = {
             "Z1": Z1,
             "A1": A1,
             "Z2": Z2,
             "A2": A2}
    
    return A2,cache

In [295]:
def compute_cost(A, Y):
    m = Y.shape[1] 
    cost = (- 1 / m) * np.sum(Y * np.log(A) + (1 - Y) * (np.log(1 - A)))
    return cost

In [296]:
def derivade_sigmoid(z):
    gz = sigmoid(z)
    return gz * (1-gz);

In [297]:
def backward(cache,parameters, X, Y):
    
    m = X.shape[1]
    
    W1 = parameters["W1"]
    W2 = parameters["W2"]
    b1 = parameters["b1"]
    b2 = parameters["b2"]
    
    Z1 = cache["Z1"] 
    A1 = cache["A1"] 
    Z2 = cache["Z2"] 
    A2 = cache["A2"] 
    
    dZ2 = A2 - Y
    dW2 = (1 / m) * np.dot(dZ2, A1.T)
    db2 = (1 / m) * np.sum(dZ2,axis=1,keepdims=True)
    
    dZ1 = np.dot(W2.T, dZ2) * derivade_sigmoid(Z1)
    dW1 = (1/m) * np.dot(dZ1, X.T)
    db1 = (1/m) * np.sum(dZ1,axis=1,keepdims=True)

    
    grads = {"dW1": dW1,
             "dW2": dW2,
             "db1": db1,             
             "db2": db2,
            }
    return grads

In [311]:
def update_parameters(parameters, grads, learning_rate=0.5):
    W1 = parameters["W1"]
    W2 = parameters["W2"]
    b1 = parameters["b1"]
    b2 = parameters["b2"]
    
   
    dW1 = grads["dW1"]
    dW2 = grads["dW2"]
    db1 = grads["db1"]
    db2 = grads["db2"]


    W1 = W1 - learning_rate * dW1
    W2 = W2 - learning_rate * dW2
    b1 = b1 - learning_rate * db1
    b2 = b2 - learning_rate * db2
    
    parameters = {"W1": W1,
                  "b1": b1,
                  "W2": W2,
                  "b2": b2}
    
    return parameters

In [312]:
def predict(X, parameters):
    m = X.shape[1]
    W1 = parameters["W1"]
    W2 = parameters["W2"]
    b1 = parameters["b1"]
    b2 = parameters["b2"]

    Y_prediction = np.zeros((m, m))
    #w = w.reshape(X.shape[0], 1)
    
    # Compute vector "A" predicting the probabilities of a cat being present in the picture
    Z1 = np.dot(W1, X) + b1
    A1 = sigmoid(Z1)
    Z2 = np.dot(W2, A1) + b2
    A2 = sigmoid(Z2)
    #print(A2)
        
    for i in range(A2.shape[0]):
        # Convert probabilities a[0,i] to actual predictions p[0,i]
        for j in range(A2.shape[1]):
            Y_prediction[i, j] = 1 if A2[i, j] >= 0.5 else 0
        
    return Y_prediction

In [313]:
def nn_model(X, Y, n_h, num_iterations=1):   
    n_x = X.shape[0]
    n_y = Y.shape[0] 
    
    # Initialize parameters, then retrieve W1, b1, W2, b2. Inputs: "n_x, n_h, n_y". Outputs = "W1, b1, W2, b2, parameters".
    parameters = initialize_parameters(n_x, n_h, n_y)
    
    for i in range(0, num_iterations):
         
        # Forward propagation. Inputs: "X, parameters". Outputs: "A2, cache".
        A2, cache = forward(X, parameters)
        
        # Cost function. Inputs: "A2, Y, parameters". Outputs: "cost".
        cost = compute_cost(A2, Y)
 
        # Backpropagation. Inputs: "parameters, cache, X, Y". Outputs: "grads".
        grads = backward(cache, parameters, X, Y)
 
        # Gradient descent parameter update. Inputs: "parameters, grads". Outputs: "parameters".
        parameters = update_parameters(parameters, grads)
        
        # Print the cost every 1000 iterations
        if i % 100 == 0:
            print ("Cost after iteration %i: %f" % (i, cost))
            
    #print("A2; ",A2)
    Y_prediction = predict(X,parameters)
    print("------------------")
    print("Prediccion:")
    print(Y_prediction)

    return parameters

In [314]:
X = np.identity(15, dtype = float)#np.array([[0,0],[0,1],[1,0],[1,1]])
Y = X
print(X.T)
print(Y)
print(X.shape)
print(Y.shape)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0

In [315]:
n_x = X.shape[0]
n_y = Y.shape[0] 

In [317]:
parameterss = nn_model(X, Y, 4, num_iterations=3000)

Cost after iteration 0: 10.405536
Cost after iteration 100: 3.673852
Cost after iteration 200: 3.673546
Cost after iteration 300: 3.672370
Cost after iteration 400: 3.667705
Cost after iteration 500: 3.648446
Cost after iteration 600: 3.563958
Cost after iteration 700: 3.267104
Cost after iteration 800: 2.774497
Cost after iteration 900: 2.341968
Cost after iteration 1000: 2.035768
Cost after iteration 1100: 1.814850
Cost after iteration 1200: 1.643993
Cost after iteration 1300: 1.502633
Cost after iteration 1400: 1.380411
Cost after iteration 1500: 1.273134
Cost after iteration 1600: 1.179122
Cost after iteration 1700: 1.096848
Cost after iteration 1800: 1.024541
Cost after iteration 1900: 0.960482
Cost after iteration 2000: 0.903213
Cost after iteration 2100: 0.851579
Cost after iteration 2200: 0.804695
Cost after iteration 2300: 0.761900
Cost after iteration 2400: 0.722698
Cost after iteration 2500: 0.686692
Cost after iteration 2600: 0.653532
Cost after iteration 2700: 0.622892
Cos