In [1]:
import numpy as np
import csv

In [2]:
def sigmoid(z):
    s = 1 / (1 + np.exp(-z))
    return s

In [3]:
def initialize_parameters(n_x, n_h, n_y):
    np.random.seed(1)
    
    W1 = np.random.normal(0, 1, (n_h, n_x)) #W1 -- weight matrix of shape (n_h, n_x)
    b1 = np.random.random((n_h, 1))         #b1 -- bias vector of shape (n_h, 1)
    W2 = np.random.normal(0, 1, (n_y, n_h)) #W2 -- weight matrix of shape (n_y, n_h)
    b2 = np.random.random((n_y, 1))         #b2 -- bias vector of shape (n_y, 1)


    parameters = {"W1": W1,
                  "b1": b1,
                  "W2": W2,
                  "b2": b2}
    
    return parameters

In [4]:
def forward(X,Y,parameters,pred=False):
    
    W1 = parameters["W1"]
    W2 = parameters["W2"]
    b1 = parameters["b1"]
    b2 = parameters["b2"]
    
    Z1 = np.dot(W1, X) + b1
    A1 = sigmoid(Z1)
    Z2 = np.dot(W2, A1) + b2
    A2 = sigmoid(Z2)
    
    if pred:
        Y_prediction = np.zeros((Y.shape[0], Y.shape[1]))
        for i in range(A2.shape[0]):
            # Convert probabilities a[0,i] to actual predictions p[0,i]
            for j in range(A2.shape[1]):
                Y_prediction[i, j] = 1 if A2[i, j] >= 0.5 else 0
        return Y_prediction
    
    
    cache = {
             "Z1": Z1,
             "A1": A1,
             "Z2": Z2,
             "A2": A2}
    
    return A2,cache

In [5]:
def compute_cost(A, Y):
    m = Y.shape[1] 
    cost = (- 1 / m) * np.sum(Y * np.log(A) + (1 - Y) * (np.log(1 - A)))
    return cost

In [6]:
def derivade_sigmoid(z):
    gz = sigmoid(z)
    return gz * (1-gz);

In [7]:
def backward(cache,parameters, X, Y):
    
    m = X.shape[1]
    
    W1 = parameters["W1"]
    W2 = parameters["W2"]
    b1 = parameters["b1"]
    b2 = parameters["b2"]
    
    Z1 = cache["Z1"] 
    A1 = cache["A1"] 
    Z2 = cache["Z2"] 
    A2 = cache["A2"] 
    
    dZ2 = A2 - Y
    dW2 = (1 / m) * np.dot(dZ2, A1.T)
    db2 = (1 / m) * np.sum(dZ2,axis=1,keepdims=True)
    
    dZ1 = np.dot(W2.T, dZ2) * derivade_sigmoid(Z1)
    dW1 = (1/m) * np.dot(dZ1, X.T)
    db1 = (1/m) * np.sum(dZ1,axis=1,keepdims=True)

    
    grads = {"dW1": dW1,
             "dW2": dW2,
             "db1": db1,             
             "db2": db2,
            }
    return grads

In [8]:
def update_parameters(parameters, grads, learning_rate=0.5):
    W1 = parameters["W1"]
    W2 = parameters["W2"]
    b1 = parameters["b1"]
    b2 = parameters["b2"]
    
   
    dW1 = grads["dW1"]
    dW2 = grads["dW2"]
    db1 = grads["db1"]
    db2 = grads["db2"]


    W1 = W1 - learning_rate * dW1
    W2 = W2 - learning_rate * dW2
    b1 = b1 - learning_rate * db1
    b2 = b2 - learning_rate * db2
    
    parameters = {"W1": W1,
                  "b1": b1,
                  "W2": W2,
                  "b2": b2}
    
    return parameters

# MLP One Hidden Layer (Standar NN)

In [20]:
def nn_model(X, Y, n_h, num_iterations=1):   
    n_x = X.shape[0]
    n_y = Y.shape[0] 
    
    # Initialize parameters, then retrieve W1, b1, W2, b2. Inputs: "n_x, n_h, n_y". Outputs = "W1, b1, W2, b2, parameters".
    parameters = initialize_parameters(n_x, n_h, n_y)
    
    for i in range(0, num_iterations):
         
        # Forward propagation. Inputs: "X, parameters". Outputs: "A2, cache".
        A2, cache = forward(X,Y,parameters)
        
        # Cost function. Inputs: "A2, Y, parameters". Outputs: "cost".
        cost = compute_cost(A2, Y)
 
        # Backpropagation. Inputs: "parameters, cache, X, Y". Outputs: "grads".
        grads = backward(cache, parameters, X, Y)
 
        # Gradient descent parameter update. Inputs: "parameters, grads". Outputs: "parameters".
        parameters = update_parameters(parameters, grads)
        
        # Print the cost every 1000 iterations
        if i % 100 == 0:
            print ("Cost after iteration %i: %f" % (i, cost))
            
    #print("A2; ",A2)
    Y_prediction =  forward(X,Y,parameters,pred=True)
    print("------------------")
    print("Prediccion:")
    print(Y_prediction)
    if np.array_equal(Y,Y_prediction):
        print("Success Prediction")
    else:
        print("Un - success Prediction")

    return parameters

# Auto-associador

In [21]:
X = np.identity(15, dtype = float)#np.array([[0,0],[0,1],[1,0],[1,1]])
Y = X
print(X)
print(Y)
print(X.shape)
print(Y.shape)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0

In [22]:
n_x = X.shape[0]
n_y = Y.shape[0] 

In [23]:
parameterss = nn_model(X, Y, 4, num_iterations=3000)

Cost after iteration 0: 17.150141
Cost after iteration 100: 3.280854
Cost after iteration 200: 2.775127
Cost after iteration 300: 2.340780
Cost after iteration 400: 2.025811
Cost after iteration 500: 1.791187
Cost after iteration 600: 1.605034
Cost after iteration 700: 1.447223
Cost after iteration 800: 1.308209
Cost after iteration 900: 1.184526
Cost after iteration 1000: 1.074625
Cost after iteration 1100: 0.978276
Cost after iteration 1200: 0.895565
Cost after iteration 1300: 0.824851
Cost after iteration 1400: 0.764060
Cost after iteration 1500: 0.711384
Cost after iteration 1600: 0.665351
Cost after iteration 1700: 0.624787
Cost after iteration 1800: 0.588757
Cost after iteration 1900: 0.556521
Cost after iteration 2000: 0.527486
Cost after iteration 2100: 0.501180
Cost after iteration 2200: 0.477221
Cost after iteration 2300: 0.455297
Cost after iteration 2400: 0.435155
Cost after iteration 2500: 0.416583
Cost after iteration 2600: 0.399404
Cost after iteration 2700: 0.383468
Cos

# OU-EXCLUSIVO

In [24]:
X = np.array([[0,1],[1,0],[1,1],[0,0]])
Y = np.array([[1],[1],[0],[0]])
X = X.T
Y = Y.T
print(X.shape)
print(Y.shape)

(2, 4)
(1, 4)


In [25]:
parameterss = nn_model(X, Y, 3, num_iterations=1200)

Cost after iteration 0: 0.712207
Cost after iteration 100: 0.674160
Cost after iteration 200: 0.634689
Cost after iteration 300: 0.565417
Cost after iteration 400: 0.389802
Cost after iteration 500: 0.185811
Cost after iteration 600: 0.105154
Cost after iteration 700: 0.070196
Cost after iteration 800: 0.051743
Cost after iteration 900: 0.040596
Cost after iteration 1000: 0.033221
Cost after iteration 1100: 0.028017
------------------
Prediccion:
[[1. 1. 0. 0.]]
Success Prediction
