In [1]:
import numpy as np

In [2]:
def limiter(x):
    if x > 0:
        return 1
    else:
        return 0

In [3]:
def weight_init(dim):
    w = np.zeros(shape=(dim, 1))
    b = 0
    return w,b

In [4]:
def weight_adjustment(w,y_pred,yi,xi):
    m = w.shape[0]
    learning_rate = 0.5
    Y_pred = np.full((m, 1), y_pred)
    _Y = np.full((m, 1), yi)
    w = w + learning_rate * np.multiply((_Y - Y_pred), xi.T)
    print(w)
    print("-----------------------------")
    return w

In [9]:
def propagate(w, b, X, Y):
    Y_pred = np.zeros(Y.shape[0])
    i = 0
    for xi in X:
        xi = np.reshape(xi, (1, 3))
        y_pred = np.matmul(xi,w)
        y_pred = limiter(y_pred[0])
        Y_pred[i] = (y_pred)
        if y_pred != (Y[i]):
            w = weight_adjustment(w,y_pred,Y[i],xi)
        i += 1
    Y_pred = np.reshape(Y_pred, (Y.shape[0], 1))
    if np.array_equal(Y_pred,Y):
        print("Fin")
        print(Y_pred)
    else:
        propagate(w, b, X, Y)

In [10]:
w,b = weight_init(3)
#X = np.array([[1,0,0],[1,0,1],[1,1,0],[1,1,1]])
#Y = np.array([[0],[0],[0],[1]])

X = np.array([[1,0,0],[1,0,1],[1,1,0],[1,1,1]])
Y = np.array([[0],[1],[1],[1]])
propagate(w, b, X, Y)

[[0.5]
 [0. ]
 [0.5]]
-----------------------------
[[0. ]
 [0. ]
 [0.5]]
-----------------------------
[[0.5]
 [0.5]
 [0.5]]
-----------------------------
[[0. ]
 [0.5]
 [0.5]]
-----------------------------
Fin
[[0.]
 [1.]
 [1.]
 [1.]]
